- when: bird_enabled
  block:

    - name: Setup
      include_tasks: setup.yml

    - name: Set ASN Type
      set_fact:
        two_byte_asn: "{{ inet_asn <= 65535 }}"

    - name: Create configs
      include_tasks: configs.yml

    - name: Validate bird configuration
      command: bird -p -c {{ bird_main_config }}
      register: bird_config_check
      changed_when: false
      failed_when: bird_config_check.rc != 0

    - name: Enable and run daemon
      systemd:
        name: bird
        state: started
        enabled: true
